version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
