version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
